import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { TimelineProvider } from "@/context/TimelineContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#1e3a34] text-slate-800`}
      data-theme="light"
    >
      <body className="min-h-screen flex flex-col bg-[#f8fafc]">
        <Navbar />
        <TimelineProvider>
          <main className="flex-grow w-full min-h-[calc(100vh-350px)] flex flex-col">
            {children}
          </main>
        </TimelineProvider>
        <Footer />
        <ToastContainer position="bottom-right" autoClose={3000} />
      </body>
    </html>
  );
}
